import { createContext, useContext, useState, useEffect, useCallback } from 'react'

const STORAGE_KEY = 'nbaurum_mkt_lang'

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      whoWeAre: 'Who we are',
      pricing: 'Pricing',
      faq: 'FAQ',
      contact: 'Contact',
      login: 'Login',
      getStarted: 'Get started',
      menu: 'Menu',
    },
    topbar: {
      language: 'English',
    },
    service: {
      strategicLiaison: 'Strategic Liaison & Documentation',
      aggressivePayment: 'Aggressive Payment Realization',
      disputeClaim: 'Dispute & Claim Management',
      misReporting: 'MIS, Reporting & Compliance',
      aiSaaS: 'AI Integrated SaaS Platform',
    },
    home: {
      hero: {
        slide1: {
          eyebrow: 'Payment Collections & Consultancy',
          title: 'Your Trusted Partner in Payment Collections & Consultancy',
          lead: "Specialization in Power, Solar, Telecom, Railways, PSU's & Government Projects – PAN India",
          tagline: '20+ Years Expertise | Proven Results | Integrity First',
          ctaPrimary: 'Get in touch',
          ctaSecondary: 'Get started',
        },
        slide2: {
          eyebrow: 'Enterprise Collections',
          title: 'Disciplined Collections with Full Auditability',
          lead: 'Structure invoicing, track receivables, and run collections with enterprise-grade controls.',
          tagline: 'MIS & Compliance | Single Point of Contact',
          ctaPrimary: 'Learn more',
          ctaSecondary: 'Contact',
        },
        slide3: {
          eyebrow: 'PAN India Coverage',
          title: 'Power, Solar, Telecom, Railways & Government',
          lead: 'Strategic liaison, aggressive payment realization, and dispute management across sectors.',
          tagline: 'Set processes right the first time',
          ctaPrimary: 'Our services',
          ctaSecondary: 'Get in touch',
        },
        slide4: {
          eyebrow: 'Solar & Renewable Energy',
          title: 'Expert Support for Solar & Power Sector Projects',
          lead: 'From progressive bills to final closure—we help you navigate timelines and realize payments.',
          tagline: 'Renewable energy | State boards & utilities',
          ctaPrimary: 'Our services',
          ctaSecondary: 'Contact',
        },
        slide5: {
          eyebrow: 'Telecom & Infrastructure',
          title: 'Collections & Liaison for Telecom & Infrastructure',
          lead: 'Dedicated follow-ups, dispute resolution, and compliance-ready reporting for your projects.',
          tagline: 'Single point of contact | Full transparency',
          ctaPrimary: 'Learn more',
          ctaSecondary: 'Get in touch',
        },
        slide6: {
          eyebrow: 'Trusted by Enterprises',
          title: 'Enterprise-Grade Controls & Compliance Ready',
          lead: 'Hardened processes, clear authorization, and audit-ready documentation for B2G projects.',
          tagline: 'PSU & government projects | Your goal, our duty',
          ctaPrimary: 'Get in touch',
          ctaSecondary: 'Pricing',
        },
      },
      search: {
        selectStateCity: 'Select State, City',
        sectorType: 'Sector Type',
        serviceType: 'Service Type',
        explore: 'Explore',
      },
      updates: {
        latest: 'Latest',
        update1: 'New: AI-integrated SaaS platform for AR management now available',
        update2: 'Expanded PAN India coverage for Solar & Power sector collections',
        update3: 'Strategic Liaison & Documentation – enhanced utility coordination',
        update4: 'No Collection, No Fee model for overdue recovery',
        update5: 'MIS, Reporting & Compliance – single point of contact',
        update6: 'Dispute & Claim Management – diplomatic negotiation focus',
        update7: '20+ years expertise in Railways, PSU & Government projects',
        update8: 'Aggressive Payment Realization – lifecycle billing & retention release',
      },
      services: {
        heading: 'Core Services We Provide',
        lead: 'Our comprehensive suite of services addresses every stage of the B2G payment lifecycle, from initial documentation to final fund realization. We act as your strategic partner, navigating the complex bureaucratic landscape so your team can focus on core business operations.',
        strategicLiaison: {
          title: 'Strategic Liaison & Documentation',
          utilityCoordination: 'Utility & Authority Coordination:',
          utilityDesc: 'Acts as the primary interface with State Electricity Boards, Railways, Solar, PSU and Telecom customers.',
          technicalSubmission: 'Technical Submission:',
          technicalDesc: 'Management of tender documents, Bank Guarantees (BGs), technical drawings and documentation compliance.',
          operationalStreamlining: 'Operational Streamlining:',
          operationalDesc: 'Oversight of inspection report submission and issuance of Delivery Instructions (DI) to prevent project delays.',
          viewMore: 'View More',
        },
        aggressivePayment: {
          title: 'Aggressive Payment Realization',
          lifecycleBilling: 'Lifecycle Billing:',
          lifecycleDesc: 'Persistent follow-up for progressive payments and final bills.',
          assetRecovery: 'Asset Recovery:',
          assetDesc: 'Dedicated focus on release of retention money, EMD, Advance Bank Guarantees and Performance Bank Guarantees.',
          riskFreeCollection: 'Risk-Free Collection:',
          riskFreeDesc: 'Specialized overdue payment recovery provided on a "No Collection, No Fee" basis.',
          viewMore: 'View More',
        },
        disputeClaim: {
          title: 'Dispute & Claim Management',
          resolutionExpert: 'Resolution Expert:',
          resolutionDesc: 'Handling contractual disputes, penalties and late delivery (L.D.) charges to avoid costly arbitration or legal intervention.',
          caseAssessment: 'Case Assessment:',
          caseDesc: 'Comprehensive analysis of debtor history to distinguish cash-flow issues and deliberate stalling.',
          diplomaticNegotiation: 'Diplomatic Negotiation:',
          diplomaticDesc: 'Firm yet courteous negotiation to recover funds while preserving long-term business relationships.',
          viewMore: 'View More',
        },
        misReporting: {
          title: 'MIS, Reporting & Compliance',
          dataTransparency: 'Data Transparency:',
          dataDesc: 'Regular MIS reports including invoice trackers, aging analysis and reconciliation statements.',
          fullCompliance: 'Full Compliance:',
          complianceDesc: 'Activities adhere strictly to policy, documentation standards and ethical recovery practices.',
          singlePoint: 'Single Point of Contact:',
          singlePointDesc: 'Dedicated team managing stakeholders while internal resources focus on growth.',
          viewMore: 'View More',
        },
        aiSaaS: {
          title: 'AI Integrated SaaS Platform for AR Management',
          intelligentAutomation: 'Intelligent Automation:',
          intelligentDesc: 'AI-powered workflows for invoice processing, aging analysis, and automated follow-up reminders to accelerate collections.',
          realTimeDashboards: 'Real-Time Dashboards:',
          realTimeDesc: 'Comprehensive AR dashboards with real-time visibility into receivables, DSO metrics, and collection performance.',
          viewMore: 'View More',
        },
      },
      showcase: {
        eyebrow: 'Sectors We Serve',
        title: 'Our Work in Action',
        lead: 'Sectors and projects we serve across PAN India',
        powerUtilities: 'Power & Utilities',
        powerCaption: 'State Electricity Boards & utilities',
        solarProjects: 'Solar Projects',
        solarCaption: 'Renewable energy & solar sector',
        telecom: 'Telecom',
        telecomCaption: 'Telecom & infrastructure',
        railways: 'Railways',
        railwaysCaption: 'Railway projects & PSUs',
        psuGovernment: 'PSU & Government',
        psuCaption: 'PSU & government projects',
        consultancy: 'Consultancy',
        consultancyCaption: 'Documentation & liaison',
      },
      strengths: {
        heading: 'Our Strategic Strengths',
        lead: 'What sets NB Aurum Solutions apart is not just our service offerings, but the depth of expertise and strategic approach we bring to every engagement. With decades of specialized experience in the B2G sector, we\'ve developed proprietary methodologies that consistently deliver superior results for our clients.',
        strength1: {
          title: 'Unmatched Domain Expertise',
          subtitle1: 'Targeted Sector Experience:',
          text1: 'We possess decades of hands-on experience navigating the specific payment cycles, bureaucratic processes, and operational nuances of Government Companies, Railways, and Public Sector Units across India.',
          subtitle2: 'Deep Process Knowledge:',
          text2: 'We go far beyond simple follow-ups by establishing comprehensive internal reporting processes that dramatically improve overall MIS accuracy, financial forecasting, and corporate performance metrics.',
        },
        strength2: {
          title: 'Nationwide Operational Capability',
          subtitle1: 'PAN India Network:',
          text1: 'Our operational reach extends across every state in India, supported by an extensive network of expert professionals who understand regional nuances, local protocols, and state-specific administrative procedures.',
          subtitle2: 'Effective Relationship Management:',
          text2: 'We focus on developing strong, professional relationships with key decision-makers at every level, enabling us to find a "way out" for even the most complex payment bottlenecks and bureaucratic deadlocks.',
        },
        strength3: {
          title: 'Integrity-First Philosophy',
          subtitle1: 'Process-Driven Success:',
          text1: 'We believe in setting processes right the first time to ensure full policy compliance, complete documentation, and ethical recovery practices that protect your reputation and build trust with government entities.',
          subtitle2: 'Resilient Attitude:',
          text2: 'Our signature "Never Say No" approach ensures we thrive in the most complex environments, persistently working through challenges to achieve 95% realization for our clients without compromising professional standards.',
        },
        metrics: {
          years: '20+',
          yearsTitle: 'Years of Experience',
          yearsDesc: 'Two decades navigating B2G payment landscapes',
          realization: '95%',
          realizationTitle: 'Realization Goal',
          realizationDesc: 'Committed to complete payment recovery',
          upfront: '0',
          upfrontTitle: 'Upfront Costs',
          upfrontDesc: 'Risk-free "No Collection, No Fee" model',
        },
      },
      benefits: {
        heading: 'Key Benefits of Partnership',
        intro: 'Partnering with NB Aurum Solutions delivers measurable financial and operational advantages that directly impact your bottom line. Our clients consistently report significant improvements in cash flow velocity, reduced bad debt provisioning, and enhanced working capital availability for new project investments.',
        costMinimization: 'Operating Cost Minimization',
        costMinimizationDesc: 'Convert fixed overhead into performance-based variable costs',
        badDebts: 'Bad Debts Reduction',
        badDebtsDesc: 'Proactive recovery prevents write-offs and provisioning',
        improvedDSO: 'Improved DSO & Cash Flow',
        improvedDSODesc: 'Accelerated collections reduce Days Sales Outstanding',
        dataConfidentiality: 'Data Confidentiality',
        dataConfidentialityDesc: 'Complete security of sensitive business information',
        costSavings: 'Cost Savings',
        costSavingsDesc: 'Eliminate traveling costs and manpower allocation',
        increasedRecoveries: 'Increased Recoveries',
        increasedRecoveriesDesc: 'Higher realization rates through expert navigation',
        fullContractClosure: 'Full Contract Closure',
        fullContractClosureDesc: 'Support until complete project and payment finalization',
        teamFocus: 'Team Focus',
        teamFocusDesc: 'Your staff concentrates on core competencies',
      },
      outsource: {
        heading: 'Why Companies Are Outsourcing',
        lead: 'Regulatory compliance complexity, focus on core competencies, and specialized expertise drive outsourcing decisions. In payment collections—especially with Government, PSUs, and utilities—companies face lengthy cycles, strict documentation, and relationship-heavy follow-ups. Outsourcing lets internal teams concentrate on delivery and growth while specialists handle liaison, dispute resolution, and recovery, often with better success rates and a variable cost structure that aligns with results.',
        comparisonHeading: 'In-House vs. Outsourced: A Detailed Comparison',
        comparisonSubtitle: 'Compare total cost of ownership, success rates, and strategic impact.',
        comparison: {
          feature: 'Feature',
          inHouse: 'In-House Team',
          nbaurum: 'NB Aurum Solutions',
          costStructure: 'Cost Structure',
          costStructureInHouse: 'High fixed costs: Salaries, benefits, office space, travel expenses',
          costStructureNbaurum: 'Variable costs: Performance-based \'No Collection, No Fee\' model',
          expertiseLevel: 'Expertise Level',
          expertiseLevelInHouse: 'Generalists good at accounting but lack on-ground liaison skills',
          expertiseLevelNbaurum: 'Specialists with deep-rooted knowledge of PSU/Utility protocols',
          scalability: 'Scalability',
          scalabilityInHouse: 'Difficult: Hiring staff for project surges is slow and costly',
          scalabilityNbaurum: 'Instant: Handle multiple states and high volumes immediately',
          teamFocus: 'Team Focus',
          teamFocusInHouse: 'Divided: Busy with new billings, payroll, and internal audits',
          teamFocusNbaurum: 'Dedicated: 95% focus on moving your file and realizing payment',
          relationshipRisk: 'Relationship Risk',
          relationshipRiskInHouse: 'High: Direct follow-ups can create friction with clients',
          relationshipRiskNbaurum: 'Low: Acts as professional mediator/buffer, preserving brand image',
          successRate: 'Success Rate',
          successRateInHouse: 'Often stalls at follow-up stage due to lack of local presence',
          successRateNbaurum: 'High success via \'Pole-to-Pole\' on-ground persistence',
          recoveryRate: 'Recovery Rate',
          recoveryRateInHouse: '60-70% with manual follow-ups',
          recoveryRateNbaurum: '90-100% with expert liaison and specialized tracking',
          dso: 'DSO (Days Sales Outstanding)',
          dsoInHouse: '120+ days typical cycle time',
          dsoNbaurum: '60-90 days accelerated realization',
          badDebtRisk: 'Bad Debt Risk',
          badDebtRiskInHouse: 'High: Files often get \'forgotten\' in routine workflows',
          badDebtRiskNbaurum: 'Minimal: Persistent tracking prevents aging into write-offs',
          legalCost: 'Legal/Arbitration Cost',
          legalCostInHouse: 'High if disputes aren\'t mediated effectively',
          legalCostNbaurum: 'Low: Pre-legal mediation expertise resolves most issues',
        },
        timeValue: {
          heading: 'Time-Value of Money Analysis',
          text: 'In the Solar and Power sectors, where capital costs are high, delayed collections have a real financial impact. If ₹5 Crores is stuck with a DISCOM for an extra 6 months, the cost of capital at 10% interest equals ₹25 Lakhs in lost interest and working capital alone. NB Aurum Solutions\' \'Pole-to-Pole\' persistence reduces collection cycles by 30-45%, saving clients lakhs in interest costs that often exceed our success fee—making the partnership cashflow positive from day one.',
        },
        costBenefit: {
          title: 'Cost–Benefit Analysis',
          subtitle: 'Understanding the financial and strategic advantages of partnering with NB Aurum Solutions',
          timeValue: 'Time-Value of Money',
          timeValueDesc: 'Faster recovery reduces interest loss and improves working capital velocity, enabling reinvestment in growth opportunities.',
          opportunityCost: 'Opportunity Cost',
          opportunityCostDesc: 'Engineering teams focus on growth and innovation instead of administrative follow-ups and collection activities.',
          fixedVsVariable: 'Fixed vs Variable Cost',
          fixedVsVariableDesc: 'Eliminates salary liabilities, infrastructure costs, travel expenses, and payment risk when recovery fails.',
          comparativeROI: 'Comparative ROI',
          comparativeROIDesc: 'Higher recovery rates, reduced DSO, lower bad-debt risk, reduced legal costs, and improved working capital.',
        },
        strategicNecessity: {
          title: 'Strategic Necessity of Third-Party Collection',
          subtitle: 'Key advantages that make outsourcing collections a strategic imperative',
          professionalNeutrality: 'Professional neutrality',
          conversionCosts: 'Conversion of fixed to variable costs',
          specializedIntelligence: 'Specialized liaison intelligence',
          coreCompetencies: 'Focus on core competencies',
          cashFlowVelocity: 'Improved cash-flow velocity',
          badDebtProvisioning: 'Reduced bad debt provisioning',
          disputeMediation: 'Advanced dispute mediation',
          agingAnalysis: 'Data-driven aging analysis',
          businessContinuity: 'Business continuity',
          regulatoryCompliance: 'Regulatory and audit compliance',
        },
      },
      system: {
        heading: 'See Our System in Action',
        lead: 'Experience our AI-integrated SaaS platform for AR management',
        dashboardTitle: 'AR Management Dashboard',
        live: 'Live',
        totalReceivables: 'Total Receivables',
        dso: 'DSO',
        collectionRate: 'Collection Rate',
        pendingActions: 'Pending Actions',
        vsLastMonth: 'vs last month',
        improvement: 'improvement',
        thisQuarter: 'this quarter',
        requireFollowUp: 'require follow-up',
        collectionPerformance: 'Collection Performance',
        thisMonth: 'This Month',
        lastMonth: 'Last Month',
        recentInvoices: 'Recent Invoices',
        viewAll: 'View All',
        invoice: 'Invoice #',
        client: 'Client',
        amount: 'Amount',
        status: 'Status',
        dueDate: 'Due Date',
        paid: 'Paid',
        pending: 'Pending',
        inProcess: 'In Process',
        aiPoweredInsights: 'AI-Powered Insights',
        aiPoweredDesc: 'Automated aging analysis and intelligent follow-up reminders',
        realTimeDashboards: 'Real-Time Dashboards',
        realTimeDashboardsDesc: 'Comprehensive visibility into receivables and DSO metrics',
        automatedWorkflows: 'Automated Workflows',
        automatedWorkflowsDesc: 'Streamlined invoice processing and collection tracking',
        complianceReady: 'Compliance Ready',
        complianceReadyDesc: 'Full audit trail and documentation standards',
      },
      cashflow: {
        heading: 'Ready to Secure Your Cash Flow?',
        desc: 'Don\'t let customer delays and complex documentation stall your company\'s growth trajectory. Partner with NB Aurum Solutions to transform your pending receivables into liquid working capital that fuels expansion, innovation, and competitive advantage.',
        zeroRisk: 'Zero Risk Model',
        zeroRiskDesc: '"No Collection, No Fee" for all overdue recoveries',
        sectorExperts: 'Sector Experts',
        sectorExpertsDesc: '20+ years in Power, Solar, Telecom, Railways, and PSUs',
        endToEnd: 'End-to-End Service',
        endToEndDesc: 'From tender documentation to final PBG release',
        reputationFirst: 'Reputation First',
        reputationFirstDesc: 'Diplomatic approach preserving client relationships',
        getStarted: 'Get started',
        getInTouch: 'Get in touch',
      },
      faq: {
        heading: 'Frequently Asked Questions',
        subtitle: 'Quick answers about our collections, consultancy, and engagement model.',
        q1: 'Will your recovery process damage our long-term relationship with DISCOMs or PSUs?',
        a1: 'No. We employ a "Diplomatic Caution" strategy. We recognize that these agencies are your future clients. Our approach focuses on resolving documentation bottlenecks and procedural hurdles through professional negotiation, ensuring your reputation remains intact for future tenders.',
        q2: 'How does the "No Collection, No Fee" model work?',
        a2: 'This is a 95% risk-free model for overdue recovery. You pay no upfront service fees; our success fee is a pre-agreed percentage of the amount actually realized in your bank account. If we don\'t collect, you don\'t pay. (Note: Fixed-fee structures apply only to ongoing technical liaison or tender management services).',
        q3: 'Why outsource if we already have an internal accounts department?',
        a3: 'Internal teams are often desk-bound. We provide the "On-Ground" presence required to move files through PSU bureaucracies. Outsourcing converts your fixed overhead costs into a variable, performance-based expense, freeing your team for core financial planning and execution.',
        q4: 'How do you improve DSO and cash flow specifically in the Power and Solar sectors?',
        a4: 'We aggressively yet compliantly chase progressive payments, final bills, and the release of Retention/PBGs. By minimizing delays from utilities and DISCOMs, we reduce your Days Sales Outstanding (DSO) and cut bad debts, enhancing the liquidity you need to reinvest in new projects.',
        q5: 'How do you handle disputed payments or L.D. (Late Delivery) penalties?',
        a5: 'We deep-dive into the contract and payer history. By identifying if a delay was due to bureaucratic hurdles rather than vendor fault, we provide the necessary documentation to mitigate penalties and resolve disputes without reaching expensive legal arbitration.',
        q6: 'Can you help with the release of old Retention Money and PBGs?',
        a6: 'Yes. This is one of our core strengths. We specialize in tracking down long-pending Retention funds and Performance Bank Guarantees (PBG) that often get "stuck" in the system years after project completion.',
        q7: 'How do we stay updated on the status of our cases?',
        a7: 'Transparency is a pillar of our service. You will receive regular MIS (Management Information System) reports, including aging analysis and detailed status notes for every invoice, giving you a clear, data-driven view of your receivables.',
        q8: 'What is your "Pole-to-Pole" service model?',
        a8: 'It refers to our end-to-end involvement—from the "first pole" (Tender and Technical Documentation) to the "last pole" (Final payment realization and contract closure). We manage the entire lifecycle to ensure no financial leakage occurs at any stage.',
        q9: 'How do you categorize "Deliberate" vs. "Genuine" payment delays?',
        a9: 'We use 20+ years of payer history and local intelligence to categorize delays. If a delay is genuine (budget issues), we negotiate a realistic payment timeline. If it is deliberate (administrative stalling), we escalate the matter through the appropriate diplomatic and official channels.',
        q10: 'Is your service limited to any state or is it PAN-India?',
        a10: 'While we are proudly based in Jaipur, our network and operational capability are PAN-India. We have the expertise and local reach to follow up with utilities and government departments in any state across the country.',
        q11: 'How do you handle cases where the government department claims "lack of budget" or "funds not received from the center"?',
        a11: 'This is where our niche intelligence comes in. We don\'t just take "no" for an answer. We track the flow of funds through state and central allocations. Often, we help the department prioritize your file by ensuring all compliance documents are "payment-ready," making it easier for them to utilize available funds for your invoice over others that are incomplete.',
        q12: 'Is your approach purely manual, or do you use technology for tracking?',
        a12: 'We use a hybrid approach. While the final "push" is always personal and diplomatic, we utilize internal tracking tools to monitor aging cycles and payment milestones. This allows us to provide you with data-driven MIS reports that help your CFO forecast cash flow with much higher accuracy.',
        q13: 'How do you assist in the "Closure" phase of a contract?',
        a13: 'Most agencies stop at invoice collection. We handle the "Last Mile" closure, which includes the reconciliation of accounts, obtaining "No Dues Certificates," and the vital task of releasing long-stalled Performance Bank Guarantees (PBGs). We ensure the contract is closed legally and financially in the department\'s records.',
        q14: 'Can you help us with GST and Tax-related payment reconciliations?',
        a14: 'Yes. Since we ensure "perfect documentation" for every payment, we help align your realizations with GST filings. We ensure that the department provides the necessary certificates (like TDS or GST TDS certificates) so that your tax audits remain clean and your input tax credits are protected.',
        q15: 'What are the key benefits of outsourcing to NB Aurum Solutions?',
        a15: '• Reduction/elimination of overdue payments and bad debts\n• Faster collections, better stakeholder relationships via diplomatic yet firm approach\n• Systematic tracking: Invoice/aging/escalation/deduction trackers, reconciliations\n• Swift query resolution and templated reminders\n• Process automation, frequent analysis, and identification of delay causes\n• Full compliance/transparency/documentation\n• Ethical recovery preserving future business opportunities',
        q16: 'Will I lose control if I outsource payment collections to NB Aurum Solutions?',
        a16: 'No—partnership maintains your oversight. We operate per your contract guidelines, providing regular MIS (invoice trackers, aging analysis, statements). You decide scope: full end-to-end or specific activities. Transparency ensures full visibility and control.',
        viewMore: 'View More',
        viewMoreHint: 'Have another question? Ask us on the contact page.',
      },
      onboarding: {
        heading: 'Our Seamless Onboarding Process',
        getStarted: 'Get started',
        talkToUs: 'Talk to us',
      },
      arInsights: {
        heading: 'Understanding Accounts Receivable',
        lead: 'Accounts Receivable is not just about sending invoices — it\'s a structured process that connects revenue, cash flow, and customer discipline.',
        para2: 'From sales orders and invoicing to collections, customer reconciliations, and aging analysis, every step exists for a reason: to ensure timely cash inflow, reduce credit risk, and maintain financial accuracy.',
        para3: 'Learning AR has shown me that timely invoicing matters, clear credit terms matter, and consistent follow-ups matter.',
        closing: 'When managed well, Accounts Receivable strengthens working capital, protects revenue, and supports overall business stability.',
      },
    },
    about: {
      heading: 'About NB Aurum Solutions',
      lead: 'Your trusted partner in payment collections and consultancy—specializing in Power, Solar, Telecom, Railways, PSU\'s and Government projects across India.',
      mission: {
        title: 'Our Mission',
        text: 'We bring discipline, transparency, and results to payment realization and collections. We believe in set processes right the first time, strong customer relationships, full policy and document compliance, and a "Never say No" attitude—so your cash flow is secure and your contracts close cleanly.',
        standFor: 'What we stand for',
        standForText: 'NB Aurum Solutions is built on 20+ years of expertise by Professionals. We focus on strategic liaison, aggressive payment realization, dispute management, and MIS-led compliance—so you get end-to-end service from a single point of contact while your team focuses on growth.',
        whoWeAre: 'Who we are',
      },
      compliance: {
        heading: 'Compliance, security & transparency',
        lead: 'Full policy and document compliance, ethical recovery practices, and data transparency—so you can trust every step.',
        complianceControls: {
          title: 'Compliance & controls',
          text: 'Activities adhere strictly to policy, documentation standards, and ethical recovery practices. Regular MIS reports, invoice trackers, aging analysis, and reconciliation statements keep everything audit-ready.',
        },
        dataConfidentiality: {
          title: 'Data & confidentiality',
          text: 'Your business data stays confidential. We use hardened processes, clear authorization, and a single point of contact so internal resources can focus on growth while we manage liaison and recovery.',
        },
        scalability: {
          title: 'Scalability',
          text: 'PAN-India capability with a nationwide network of professionals. We scale with your project footprint—Power, Solar, Telecom, Railways, PSUs and Government—without compromising on relationship management or compliance.',
        },
      },
      values: {
        heading: 'Our journey and values',
        lead: 'From foundation to today—how we work and what we stand for.',
        howWeDeliver: {
          title: 'How we deliver',
          strategicLiaison: {
            title: 'Strategic liaison',
            text: 'Utility and authority coordination, technical submission, and operational streamlining so projects don\'t delay.',
          },
          paymentRealization: {
            title: 'Payment realization',
            text: 'Lifecycle billing, asset recovery (retention, EMD, BGs), and risk-free collection on a No Collection, No Fee basis.',
          },
          disputeClosure: {
            title: 'Dispute & closure',
            text: 'Dispute resolution, diplomatic negotiation, and support until full contract closure with reconciliation and certification.',
          },
        },
        coreValues: {
          title: 'Core values',
          value1: 'Integrity first—process-driven compliance and ethical recovery.',
          value2: 'Set processes right the first time; no shortcuts.',
          value3: 'Diplomatic yet firm negotiation to preserve long-term relationships.',
          value4: 'Full transparency through MIS and regular reporting.',
        },
      },
      differentiates: {
        heading: 'What differentiates NB Aurum Solutions',
        lead: 'Unmatched domain expertise, nationwide capability, and a reputation-preserving approach.',
        domainExpertise: {
          title: 'Domain expertise',
          text: 'Targeted sector experience in government companies, railways and PSUs. Deep process knowledge that improves internal reporting and MIS accuracy.',
        },
        panIndia: {
          title: 'PAN-India capability',
          text: 'Nationwide network of professionals and strong relationship management to resolve complex payment bottlenecks—wherever your projects are.',
        },
        riskFree: {
          title: 'Risk-free model',
          text: 'Outcome-based pricing, zero upfront cost, and performance-driven recovery. You pay when we deliver—so adoption is seamless and low-risk.',
        },
      },
      getStarted: {
        heading: 'Ready to get started?',
        lead: 'Partner with NB Aurum Solutions for disciplined payment collections and consultancy. Zero upfront cost, performance-based recovery.',
        getStarted: 'Get started',
        getInTouch: 'Get in touch',
      },
    },
    whoWeAre: {
      eyebrow: 'Our story',
      heading: 'Who we are',
      lead: 'We are your trusted partner in payment collections and consultancy—with 20+ years of expertise in Power, Solar, Telecom, Railways, PSU\'s and Government projects across India.',
      pillars: {
        heading: 'What drives us',
        why: {
          title: 'Why we do this',
          text: 'We saw teams struggle with delayed payments, stuck retention money, and complex liaison with utilities and authorities. NB Aurum Solutions exists to set processes right, recover what\'s due, and close contracts with full compliance—so you can focus on growth.',
        },
        who: {
          title: 'Who we serve',
          text: 'Companies in Power, Solar, Telecom, Railways, PSUs and Government projects—PAN India. We serve finance leaders, project teams, and operations who need aggressive payment realization, dispute resolution, and end-to-end collection support.',
        },
        how: {
          title: 'How we work',
          text: 'Dedicated liaison, regular MIS, diplomatic negotiation, and a "Never say No" attitude. We combine on-ground expertise with process-driven compliance so you get faster collections and preserved relationships.',
        },
      },
      philosophy: {
        heading: 'Our philosophy and commitment',
        lead: 'Integrity first, full compliance, and reputation-preserving recovery.',
        philosophyTitle: 'Our philosophy',
        philosophyText: 'Set processes right the first time. Build strong customer relationships. Ensure full policy and document compliance. Deliver end-to-end service. We operate with a "Never say No" attitude—so your cash flow is secured and your contracts close without friction.',
        commitmentTitle: 'What we commit to',
        diplomaticApproach: 'Diplomatic approach: Firm yet courteous negotiation to preserve long-term business relationships.',
        ethicalRecovery: 'Ethical recovery: Full transparency, MIS reporting, and compliance with policy and documentation standards.',
        riskFreeModel: 'Risk-free model: No Collection, No Fee—so you only pay when we deliver.',
        singlePoint: 'Single point of contact: Dedicated team so your internal resources focus on growth.',
      },
      values: {
        integrityFirst: 'Integrity first',
        fullCompliance: 'Full compliance',
        reputationPreserving: 'Reputation-preserving',
        neverSayNo: 'Never say No',
        panIndia: 'PAN-India',
      },
      cta: {
        heading: 'Ready to secure your cash flow?',
        lead: 'Zero risk performance model, sector expertise, and end-to-end lifecycle coverage. Your Dues. Our Duty.',
        getInTouch: 'Get in touch',
        viewEngagement: 'View engagement options',
      },
    },
  },
  hi: {
    nav: {
      home: 'होम',
      about: 'हमारे बारे में',
      services: 'सेवाएं',
      whoWeAre: 'हम कौन हैं',
      pricing: 'मूल्य निर्धारण',
      faq: 'FAQ',
      contact: 'संपर्क',
      login: 'लॉग इन',
      getStarted: 'शुरू करें',
      menu: 'मेन्यू',
    },
    topbar: {
      language: 'हिंदी',
    },
    service: {
      strategicLiaison: 'रणनीतिक संपर्क और दस्तावेज़ीकरण',
      aggressivePayment: 'आक्रामक भुगतान वसूली',
      disputeClaim: 'विवाद और दावा प्रबंधन',
      misReporting: 'MIS, रिपोर्टिंग और अनुपालन',
      aiSaaS: 'AI एकीकृत SaaS प्लेटफ़ॉर्म',
    },
    home: {
      hero: {
        slide1: {
          eyebrow: 'भुगतान संग्रह और सलाहकारी',
          title: 'भुगतान संग्रह और सलाहकारी में आपका विश्वसनीय साथी',
          lead: 'पावर, सोलर, टेलीकॉम, रेलवे, PSU और सरकारी परियोजनाओं में विशेषज्ञता – पूरे भारत में',
          tagline: '20+ वर्षों का अनुभव | सिद्ध परिणाम | ईमानदारी पहले',
          ctaPrimary: 'संपर्क करें',
          ctaSecondary: 'शुरू करें',
        },
        slide2: {
          eyebrow: 'एंटरप्राइज़ संग्रह',
          title: 'पूर्ण लेखापरीक्षा के साथ अनुशासित संग्रह',
          lead: 'इनवॉइसिंग संरचित करें, प्राप्य ट्रैक करें, और एंटरप्राइज़-ग्रेड नियंत्रण के साथ संग्रह चलाएं।',
          tagline: 'MIS और अनुपालन | एकल संपर्क बिंदु',
          ctaPrimary: 'अधिक जानें',
          ctaSecondary: 'संपर्क',
        },
        slide3: {
          eyebrow: 'पूरे भारत में कवरेज',
          title: 'पावर, सोलर, टेलीकॉम, रेलवे और सरकार',
          lead: 'रणनीतिक संपर्क, आक्रामक भुगतान वसूली, और क्षेत्रों में विवाद प्रबंधन।',
          tagline: 'पहली बार प्रक्रियाओं को सही सेट करें',
          ctaPrimary: 'हमारी सेवाएं',
          ctaSecondary: 'संपर्क करें',
        },
        slide4: {
          eyebrow: 'सोलर और नवीकरणीय ऊर्जा',
          title: 'सोलर और पावर सेक्टर परियोजनाओं के लिए विशेषज्ञ सहायता',
          lead: 'प्रगतिशील बिलों से अंतिम समापन तक—हम आपको समयसीमा नेविगेट करने और भुगतान प्राप्त करने में मदद करते हैं।',
          tagline: 'नवीकरणीय ऊर्जा | राज्य बोर्ड और उपयोगिताएं',
          ctaPrimary: 'हमारी सेवाएं',
          ctaSecondary: 'संपर्क',
        },
        slide5: {
          eyebrow: 'टेलीकॉम और बुनियादी ढांचा',
          title: 'टेलीकॉम और बुनियादी ढांचे के लिए संग्रह और संपर्क',
          lead: 'आपकी परियोजनाओं के लिए समर्पित फॉलो-अप, विवाद समाधान, और अनुपालन-तैयार रिपोर्टिंग।',
          tagline: 'एकल संपर्क बिंदु | पूर्ण पारदर्शिता',
          ctaPrimary: 'अधिक जानें',
          ctaSecondary: 'संपर्क करें',
        },
        slide6: {
          eyebrow: 'एंटरप्राइज़ द्वारा विश्वसनीय',
          title: 'एंटरप्राइज़-ग्रेड नियंत्रण और अनुपालन तैयार',
          lead: 'B2G परियोजनाओं के लिए कठोर प्रक्रियाएं, स्पष्ट अधिकार, और लेखापरीक्षा-तैयार दस्तावेज़ीकरण।',
          tagline: 'PSU और सरकारी परियोजनाएं | आपका लक्ष्य, हमारा कर्तव्य',
          ctaPrimary: 'संपर्क करें',
          ctaSecondary: 'मूल्य निर्धारण',
        },
      },
      search: {
        selectStateCity: 'राज्य, शहर चुनें',
        sectorType: 'सेक्टर प्रकार',
        serviceType: 'सेवा प्रकार',
        explore: 'अन्वेषण करें',
      },
      updates: {
        latest: 'नवीनतम',
        update1: 'नया: AR प्रबंधन के लिए AI-एकीकृत SaaS प्लेटफ़ॉर्म अब उपलब्ध है',
        update2: 'सोलर और पावर सेक्टर संग्रह के लिए विस्तारित पूरे भारत में कवरेज',
        update3: 'रणनीतिक संपर्क और दस्तावेज़ीकरण – बढ़ी हुई उपयोगिता समन्वय',
        update4: 'अतिदेय वसूली के लिए कोई संग्रह नहीं, कोई शुल्क नहीं मॉडल',
        update5: 'MIS, रिपोर्टिंग और अनुपालन – एकल संपर्क बिंदु',
        update6: 'विवाद और दावा प्रबंधन – कूटनीतिक वार्ता फोकस',
        update7: 'रेलवे, PSU और सरकारी परियोजनाओं में 20+ वर्षों का अनुभव',
        update8: 'आक्रामक भुगतान वसूली – जीवनचक्र बिलिंग और रिटेंशन रिलीज़',
      },
      services: {
        heading: 'हम प्रदान करने वाली मुख्य सेवाएं',
        lead: 'हमारी व्यापक सेवाओं का सुइट B2G भुगतान जीवनचक्र के हर चरण को संबोधित करता है, प्रारंभिक दस्तावेज़ीकरण से लेकर अंतिम निधि वसूली तक। हम आपके रणनीतिक साथी के रूप में कार्य करते हैं, जटिल नौकरशाही परिदृश्य को नेविगेट करते हैं ताकि आपकी टीम मुख्य व्यावसायिक संचालन पर ध्यान केंद्रित कर सके।',
        strategicLiaison: {
          title: 'रणनीतिक संपर्क और दस्तावेज़ीकरण',
          utilityCoordination: 'उपयोगिता और प्राधिकरण समन्वय:',
          utilityDesc: 'राज्य बिजली बोर्ड, रेलवे, सोलर, PSU और टेलीकॉम ग्राहकों के साथ प्राथमिक इंटरफ़ेस के रूप में कार्य करता है।',
          technicalSubmission: 'तकनीकी प्रस्तुति:',
          technicalDesc: 'टेंडर दस्तावेज़, बैंक गारंटी (BGs), तकनीकी ड्रॉइंग और दस्तावेज़ीकरण अनुपालन का प्रबंधन।',
          operationalStreamlining: 'परिचालन सुव्यवस्थितीकरण:',
          operationalDesc: 'परियोजना देरी को रोकने के लिए निरीक्षण रिपोर्ट प्रस्तुति और डिलीवरी निर्देश (DI) जारी करने की देखरेख।',
          viewMore: 'अधिक देखें',
        },
        aggressivePayment: {
          title: 'आक्रामक भुगतान वसूली',
          lifecycleBilling: 'जीवनचक्र बिलिंग:',
          lifecycleDesc: 'प्रगतिशील भुगतान और अंतिम बिलों के लिए लगातार फॉलो-अप।',
          assetRecovery: 'संपत्ति वसूली:',
          assetDesc: 'रिटेंशन मनी, EMD, अग्रिम बैंक गारंटी और परफॉर्मेंस बैंक गारंटी की रिलीज़ पर समर्पित फोकस।',
          riskFreeCollection: 'जोखिम-मुक्त संग्रह:',
          riskFreeDesc: '"कोई संग्रह नहीं, कोई शुल्क नहीं" आधार पर विशेष अतिदेय भुगतान वसूली प्रदान की जाती है।',
          viewMore: 'अधिक देखें',
        },
        disputeClaim: {
          title: 'विवाद और दावा प्रबंधन',
          resolutionExpert: 'समाधान विशेषज्ञ:',
          resolutionDesc: 'महंगे मध्यस्थता या कानूनी हस्तक्षेप से बचने के लिए अनुबंधात्मक विवाद, जुर्माना और देर से डिलीवरी (L.D.) शुल्क का प्रबंधन।',
          caseAssessment: 'मामले का मूल्यांकन:',
          caseDesc: 'नकदी-प्रवाह मुद्दों और जानबूझकर रुकावट को अलग करने के लिए ऋणी इतिहास का व्यापक विश्लेषण।',
          diplomaticNegotiation: 'कूटनीतिक वार्ता:',
          diplomaticDesc: 'दीर्घकालिक व्यावसायिक संबंधों को संरक्षित करते हुए धन वसूली के लिए दृढ़ लेकिन विनम्र वार्ता।',
          viewMore: 'अधिक देखें',
        },
        misReporting: {
          title: 'MIS, रिपोर्टिंग और अनुपालन',
          dataTransparency: 'डेटा पारदर्शिता:',
          dataDesc: 'इनवॉइस ट्रैकर, एजिंग विश्लेषण और समाधान विवरण सहित नियमित MIS रिपोर्ट।',
          fullCompliance: 'पूर्ण अनुपालन:',
          complianceDesc: 'गतिविधियां नीति, दस्तावेज़ीकरण मानकों और नैतिक वसूली प्रथाओं का सख्ती से पालन करती हैं।',
          singlePoint: 'एकल संपर्क बिंदु:',
          singlePointDesc: 'हितधारकों का प्रबंधन करने वाली समर्पित टीम जबकि आंतरिक संसाधन विकास पर ध्यान केंद्रित करते हैं।',
          viewMore: 'अधिक देखें',
        },
        aiSaaS: {
          title: 'AR प्रबंधन के लिए AI एकीकृत SaaS प्लेटफ़ॉर्म',
          intelligentAutomation: 'बुद्धिमान स्वचालन:',
          intelligentDesc: 'इनवॉइस प्रसंस्करण, एजिंग विश्लेषण, और संग्रह में तेजी लाने के लिए स्वचालित फॉलो-अप अनुस्मारक के लिए AI-संचालित वर्कफ़्लो।',
          realTimeDashboards: 'रीयल-टाइम डैशबोर्ड:',
          realTimeDesc: 'प्राप्य, DSO मेट्रिक्स, और संग्रह प्रदर्शन में रीयल-टाइम दृश्यता के साथ व्यापक AR डैशबोर्ड।',
          viewMore: 'अधिक देखें',
        },
      },
      showcase: {
        eyebrow: 'हम जिन सेक्टरों की सेवा करते हैं',
        title: 'कार्रवाई में हमारा काम',
        lead: 'पूरे भारत में हम जिन सेक्टरों और परियोजनाओं की सेवा करते हैं',
        powerUtilities: 'पावर और उपयोगिताएं',
        powerCaption: 'राज्य बिजली बोर्ड और उपयोगिताएं',
        solarProjects: 'सोलर परियोजनाएं',
        solarCaption: 'नवीकरणीय ऊर्जा और सोलर सेक्टर',
        telecom: 'टेलीकॉम',
        telecomCaption: 'टेलीकॉम और बुनियादी ढांचा',
        railways: 'रेलवे',
        railwaysCaption: 'रेलवे परियोजनाएं और PSU',
        psuGovernment: 'PSU और सरकार',
        psuCaption: 'PSU और सरकारी परियोजनाएं',
        consultancy: 'सलाहकारी',
        consultancyCaption: 'दस्तावेज़ीकरण और संपर्क',
      },
      strengths: {
        heading: 'हमारी रणनीतिक ताकतें',
        lead: 'जो NB Aurum Solutions को अलग बनाता है वह केवल हमारी सेवा पेशकश नहीं है, बल्कि हम हर सगाई में लाने वाली विशेषज्ञता की गहराई और रणनीतिक दृष्टिकोण है। B2G सेक्टर में दशकों के विशेष अनुभव के साथ, हमने स्वामित्व वाली पद्धतियां विकसित की हैं जो हमारे ग्राहकों के लिए लगातार श्रेष्ठ परिणाम देती हैं।',
        strength1: {
          title: 'अतुल्य डोमेन विशेषज्ञता',
          subtitle1: 'लक्षित सेक्टर अनुभव:',
          text1: 'हमारे पास भारत भर में सरकारी कंपनियों, रेलवे और सार्वजनिक क्षेत्र की इकाइयों के विशिष्ट भुगतान चक्र, नौकरशाही प्रक्रियाओं और परिचालन बारीकियों को नेविगेट करने का दशकों का व्यावहारिक अनुभव है।',
          subtitle2: 'गहरी प्रक्रिया ज्ञान:',
          text2: 'हम व्यापक आंतरिक रिपोर्टिंग प्रक्रियाओं की स्थापना करके सरल फॉलो-अप से कहीं आगे जाते हैं जो समग्र MIS सटीकता, वित्तीय पूर्वानुमान और कॉर्पोरेट प्रदर्शन मेट्रिक्स में नाटकीय रूप से सुधार करते हैं।',
        },
        strength2: {
          title: 'देशव्यापी परिचालन क्षमता',
          subtitle1: 'पूरे भारत में नेटवर्क:',
          text1: 'हमारी परिचालन पहुंच भारत के हर राज्य में फैली हुई है, विशेषज्ञ पेशेवरों के व्यापक नेटवर्क द्वारा समर्थित है जो क्षेत्रीय बारीकियों, स्थानीय प्रोटोकॉल और राज्य-विशिष्ट प्रशासनिक प्रक्रियाओं को समझते हैं।',
          subtitle2: 'प्रभावी संबंध प्रबंधन:',
          text2: 'हम हर स्तर पर प्रमुख निर्णय निर्माताओं के साथ मजबूत, पेशेवर संबंध विकसित करने पर ध्यान केंद्रित करते हैं, जो हमें सबसे जटिल भुगतान अड़चनों और नौकरशाही गतिरोधों के लिए भी "बाहर निकलने का रास्ता" खोजने में सक्षम बनाता है।',
        },
        strength3: {
          title: 'ईमानदारी-प्रथम दर्शन',
          subtitle1: 'प्रक्रिया-संचालित सफलता:',
          text1: 'हम पहली बार प्रक्रियाओं को सही सेट करने में विश्वास करते हैं ताकि पूर्ण नीति अनुपालन, पूर्ण दस्तावेज़ीकरण, और नैतिक वसूली प्रथाओं सुनिश्चित हो सकें जो आपकी प्रतिष्ठा की रक्षा करती हैं और सरकारी संस्थाओं के साथ विश्वास बनाती हैं।',
          subtitle2: 'लचीला रवैया:',
          text2: 'हमारा हस्ताक्षर "कभी न कहें" दृष्टिकोण सुनिश्चित करता है कि हम सबसे जटिल वातावरण में पनपें, पेशेवर मानकों से समझौता किए बिना हमारे ग्राहकों के लिए 95% वसूली प्राप्त करने के लिए चुनौतियों के माध्यम से लगातार काम करें।',
        },
        metrics: {
          years: '20+',
          yearsTitle: 'वर्षों का अनुभव',
          yearsDesc: 'B2G भुगतान परिदृश्यों को नेविगेट करने के दो दशक',
          realization: '95%',
          realizationTitle: 'वसूली लक्ष्य',
          realizationDesc: 'पूर्ण भुगतान वसूली के लिए प्रतिबद्ध',
          upfront: '0',
          upfrontTitle: 'अग्रिम लागत',
          upfrontDesc: 'जोखिम-मुक्त "कोई संग्रह नहीं, कोई शुल्क नहीं" मॉडल',
        },
      },
      benefits: {
        heading: 'साझेदारी के मुख्य लाभ',
        intro: 'NB Aurum Solutions के साथ साझेदारी मापने योग्य वित्तीय और परिचालन लाभ प्रदान करती है जो सीधे आपकी निचली रेखा को प्रभावित करती है। हमारे ग्राहक लगातार नकदी प्रवाह वेग में महत्वपूर्ण सुधार, कम खराब ऋण प्रावधान, और नई परियोजना निवेश के लिए बढ़ी हुई कार्यशील पूंजी उपलब्धता की रिपोर्ट करते हैं।',
        costMinimization: 'परिचालन लागत न्यूनीकरण',
        costMinimizationDesc: 'निश्चित ओवरहेड को प्रदर्शन-आधारित परिवर्तनीय लागत में परिवर्तित करें',
        badDebts: 'खराब ऋण में कमी',
        badDebtsDesc: 'सक्रिय वसूली राइट-ऑफ और प्रावधान को रोकती है',
        improvedDSO: 'बेहतर DSO और नकदी प्रवाह',
        improvedDSODesc: 'त्वरित संग्रह बिक्री के दिनों को कम करता है',
        dataConfidentiality: 'डेटा गोपनीयता',
        dataConfidentialityDesc: 'संवेदनशील व्यावसायिक जानकारी की पूर्ण सुरक्षा',
        costSavings: 'लागत बचत',
        costSavingsDesc: 'यात्रा लागत और जनशक्ति आवंटन को समाप्त करें',
        increasedRecoveries: 'बढ़ी हुई वसूली',
        increasedRecoveriesDesc: 'विशेषज्ञ नेविगेशन के माध्यम से उच्च वसूली दरें',
        fullContractClosure: 'पूर्ण अनुबंध समापन',
        fullContractClosureDesc: 'पूर्ण परियोजना और भुगतान अंतिम रूप तक सहायता',
        teamFocus: 'टीम फोकस',
        teamFocusDesc: 'आपका स्टाफ मुख्य योग्यताओं पर ध्यान केंद्रित करता है',
      },
      outsource: {
        heading: 'कंपनियां आउटसोर्सिंग क्यों कर रही हैं',
        lead: 'नियामक अनुपालन जटिलता, मुख्य योग्यताओं पर ध्यान, और विशेषज्ञ विशेषज्ञता आउटसोर्सिंग निर्णयों को चलाती है। भुगतान संग्रह में—विशेष रूप से सरकार, PSU, और उपयोगिताओं के साथ—कंपनियां लंबे चक्र, सख्त दस्तावेज़ीकरण, और संबंध-भारी फॉलो-अप का सामना करती हैं। आउटसोर्सिंग आंतरिक टीमों को वितरण और विकास पर ध्यान केंद्रित करने देती है जबकि विशेषज्ञ संपर्क, विवाद समाधान, और वसूली को संभालते हैं, अक्सर बेहतर सफलता दरों और परिणामों के साथ संरेखित परिवर्तनीय लागत संरचना के साथ।',
        comparisonHeading: 'इन-हाउस बनाम आउटसोर्स: एक विस्तृत तुलना',
        comparisonSubtitle: 'कुल स्वामित्व लागत, सफलता दर, और रणनीतिक प्रभाव की तुलना करें।',
        comparison: {
          feature: 'विशेषता',
          inHouse: 'इन-हाउस टीम',
          nbaurum: 'NB Aurum Solutions',
          costStructure: 'लागत संरचना',
          costStructureInHouse: 'उच्च निश्चित लागत: वेतन, लाभ, कार्यालय स्थान, यात्रा व्यय',
          costStructureNbaurum: 'परिवर्तनीय लागत: प्रदर्शन-आधारित \'कोई संग्रह नहीं, कोई शुल्क नहीं\' मॉडल',
          expertiseLevel: 'विशेषज्ञता स्तर',
          expertiseLevelInHouse: 'लेखांकन में अच्छे सामान्यवादी लेकिन जमीनी संपर्क कौशल की कमी',
          expertiseLevelNbaurum: 'PSU/उपयोगिता प्रोटोकॉल के गहरे ज्ञान वाले विशेषज्ञ',
          scalability: 'मापनीयता',
          scalabilityInHouse: 'मुश्किल: परियोजना उछाल के लिए स्टाफ की भर्ती धीमी और महंगी है',
          scalabilityNbaurum: 'तत्काल: तुरंत कई राज्यों और उच्च मात्रा को संभालें',
          teamFocus: 'टीम फोकस',
          teamFocusInHouse: 'विभाजित: नए बिलिंग, पेरोल, और आंतरिक लेखापरीक्षा में व्यस्त',
          teamFocusNbaurum: 'समर्पित: आपकी फ़ाइल को आगे बढ़ाने और भुगतान प्राप्त करने पर 95% फोकस',
          relationshipRisk: 'संबंध जोखिम',
          relationshipRiskInHouse: 'उच्च: प्रत्यक्ष फॉलो-अप ग्राहकों के साथ घर्षण पैदा कर सकते हैं',
          relationshipRiskNbaurum: 'कम: पेशेवर मध्यस्थ/बफर के रूप में कार्य करता है, ब्रांड छवि को संरक्षित करता है',
          successRate: 'सफलता दर',
          successRateInHouse: 'स्थानीय उपस्थिति की कमी के कारण अक्सर फॉलो-अप चरण में रुक जाता है',
          successRateNbaurum: '\'पोल-टू-पोल\' जमीनी दृढ़ता के माध्यम से उच्च सफलता',
          recoveryRate: 'वसूली दर',
          recoveryRateInHouse: 'मैनुअल फॉलो-अप के साथ 60-70%',
          recoveryRateNbaurum: 'विशेषज्ञ संपर्क और विशेष ट्रैकिंग के साथ 90-95%',
          dso: 'DSO (बिक्री के दिन बकाया)',
          dsoInHouse: '120+ दिन विशिष्ट चक्र समय',
          dsoNbaurum: '60-90 दिन त्वरित वसूली',
          badDebtRisk: 'खराब ऋण जोखिम',
          badDebtRiskInHouse: 'उच्च: फ़ाइलें अक्सर नियमित वर्कफ़्लो में \'भूल जाती हैं\'',
          badDebtRiskNbaurum: 'न्यूनतम: लगातार ट्रैकिंग राइट-ऑफ में उम्र बढ़ने को रोकती है',
          legalCost: 'कानूनी/मध्यस्थता लागत',
          legalCostInHouse: 'उच्च यदि विवादों को प्रभावी ढंग से मध्यस्थता नहीं दी जाती है',
          legalCostNbaurum: 'कम: पूर्व-कानूनी मध्यस्थता विशेषज्ञता अधिकांश मुद्दों को हल करती है',
        },
        timeValue: {
          heading: 'पैसे के समय-मूल्य विश्लेषण',
          text: 'सोलर और पावर सेक्टर में, जहां पूंजी लागत अधिक है, देरी से संग्रह का वास्तविक वित्तीय प्रभाव होता है। यदि ₹5 करोड़ एक DISCOM के साथ अतिरिक्त 6 महीने तक फंसा हुआ है, तो 10% ब्याज पर पूंजी की लागत खोई हुई ब्याज और कार्यशील पूंजी में अकेले ₹25 लाख के बराबर है। NB Aurum Solutions का \'पोल-टू-पोल\' दृढ़ता संग्रह चक्र को 30-45% कम करती है, ग्राहकों को लाखों ब्याज लागत बचाती है जो अक्सर हमारी सफलता शुल्क से अधिक होती है—दिन एक से साझेदारी को नकदी प्रवाह सकारात्मक बनाती है।',
        },
        costBenefit: {
          title: 'लागत-लाभ विश्लेषण',
          subtitle: 'NB Aurum Solutions के साथ साझेदारी के वित्तीय और रणनीतिक लाभों को समझना',
          timeValue: 'पैसे का समय-मूल्य',
          timeValueDesc: 'तेजी से वसूली ब्याज हानि को कम करती है और कार्यशील पूंजी वेग में सुधार करती है, विकास के अवसरों में पुनर्निवेश को सक्षम बनाती है।',
          opportunityCost: 'अवसर लागत',
          opportunityCostDesc: 'इंजीनियरिंग टीमें प्रशासनिक फॉलो-अप और संग्रह गतिविधियों के बजाय विकास और नवाचार पर ध्यान केंद्रित करती हैं।',
          fixedVsVariable: 'निश्चित बनाम परिवर्तनीय लागत',
          fixedVsVariableDesc: 'वेतन दायित्व, बुनियादी ढांचा लागत, यात्रा व्यय, और भुगतान जोखिम को समाप्त करता है जब वसूली विफल हो जाती है।',
          comparativeROI: 'तुलनात्मक ROI',
          comparativeROIDesc: 'उच्च वसूली दरें, कम DSO, कम खराब-ऋण जोखिम, कम कानूनी लागत, और बेहतर कार्यशील पूंजी।',
        },
        strategicNecessity: {
          title: 'थर्ड-पार्टी संग्रह की रणनीतिक आवश्यकता',
          subtitle: 'मुख्य लाभ जो आउटसोर्सिंग संग्रह को एक रणनीतिक अनिवार्य बनाते हैं',
          professionalNeutrality: 'पेशेवर तटस्थता',
          conversionCosts: 'निश्चित से परिवर्तनीय लागत में रूपांतरण',
          specializedIntelligence: 'विशेष संपर्क बुद्धिमत्ता',
          coreCompetencies: 'मुख्य योग्यताओं पर ध्यान',
          cashFlowVelocity: 'बेहतर नकदी-प्रवाह वेग',
          badDebtProvisioning: 'कम खराब ऋण प्रावधान',
          disputeMediation: 'उन्नत विवाद मध्यस्थता',
          agingAnalysis: 'डेटा-संचालित एजिंग विश्लेषण',
          businessContinuity: 'व्यावसायिक निरंतरता',
          regulatoryCompliance: 'नियामक और लेखापरीक्षा अनुपालन',
        },
      },
      system: {
        heading: 'कार्रवाई में हमारा सिस्टम देखें',
        lead: 'AR प्रबंधन के लिए हमारे AI-एकीकृत SaaS प्लेटफ़ॉर्म का अनुभव करें',
        dashboardTitle: 'AR प्रबंधन डैशबोर्ड',
        live: 'लाइव',
        totalReceivables: 'कुल प्राप्य',
        dso: 'DSO',
        collectionRate: 'संग्रह दर',
        pendingActions: 'लंबित कार्रवाई',
        vsLastMonth: 'पिछले महीने की तुलना में',
        improvement: 'सुधार',
        thisQuarter: 'इस तिमाही',
        requireFollowUp: 'फॉलो-अप की आवश्यकता है',
        collectionPerformance: 'संग्रह प्रदर्शन',
        thisMonth: 'इस महीने',
        lastMonth: 'पिछला महीना',
        recentInvoices: 'हाल की इनवॉइस',
        viewAll: 'सभी देखें',
        invoice: 'इनवॉइस #',
        client: 'ग्राहक',
        amount: 'राशि',
        status: 'स्थिति',
        dueDate: 'नियत तारीख',
        paid: 'भुगतान किया गया',
        pending: 'लंबित',
        inProcess: 'प्रक्रिया में',
        aiPoweredInsights: 'AI-संचालित अंतर्दृष्टि',
        aiPoweredDesc: 'स्वचालित एजिंग विश्लेषण और बुद्धिमान फॉलो-अप अनुस्मारक',
        realTimeDashboards: 'रीयल-टाइम डैशबोर्ड',
        realTimeDashboardsDesc: 'प्राप्य और DSO मेट्रिक्स में व्यापक दृश्यता',
        automatedWorkflows: 'स्वचालित वर्कफ़्लो',
        automatedWorkflowsDesc: 'सुव्यवस्थित इनवॉइस प्रसंस्करण और संग्रह ट्रैकिंग',
        complianceReady: 'अनुपालन तैयार',
        complianceReadyDesc: 'पूर्ण लेखापरीक्षा निशान और दस्तावेज़ीकरण मानक',
      },
      cashflow: {
        heading: 'अपने नकदी प्रवाह को सुरक्षित करने के लिए तैयार हैं?',
        desc: 'ग्राहक देरी और जटिल दस्तावेज़ीकरण को अपनी कंपनी की विकास प्रक्षेपवक्र को रोकने न दें। विस्तार, नवाचार और प्रतिस्पर्धात्मक लाभ को बढ़ावा देने वाली तरल कार्यशील पूंजी में अपने लंबित प्राप्य को बदलने के लिए NB Aurum Solutions के साथ साझेदारी करें।',
        zeroRisk: 'शून्य जोखिम मॉडल',
        zeroRiskDesc: 'सभी अतिदेय वसूली के लिए "कोई संग्रह नहीं, कोई शुल्क नहीं"',
        sectorExperts: 'सेक्टर विशेषज्ञ',
        sectorExpertsDesc: 'पावर, सोलर, टेलीकॉम, रेलवे, और PSU में 20+ वर्ष',
        endToEnd: 'अंत-से-अंत सेवा',
        endToEndDesc: 'टेंडर दस्तावेज़ीकरण से लेकर अंतिम PBG रिलीज़ तक',
        reputationFirst: 'प्रतिष्ठा पहले',
        reputationFirstDesc: 'ग्राहक संबंधों को संरक्षित करने वाला कूटनीतिक दृष्टिकोण',
        getStarted: 'शुरू करें',
        getInTouch: 'संपर्क करें',
      },
      arInsights: {
        heading: 'प्राप्य खातों को समझना',
        lead: 'प्राप्य खाते केवल इनवॉइस भेजने के बारे में नहीं हैं — यह एक संरचित प्रक्रिया है जो राजस्व, नकदी प्रवाह और ग्राहक अनुशासन को जोड़ती है।',
        para2: 'बिक्री ऑर्डर और इनवॉइसिंग से लेकर संग्रह, ग्राहक समाधान और एजिंग विश्लेषण तक, हर कदम एक कारण से मौजूद है: समय पर नकदी प्रवाह सुनिश्चित करना, क्रेडिट जोखिम कम करना और वित्तीय सटीकता बनाए रखना।',
        para3: 'AR सीखने ने मुझे दिखाया है कि समय पर इनवॉइसिंग मायने रखती है, स्पष्ट क्रेडिट शर्तें मायने रखती हैं, और लगातार फॉलो-अप मायने रखते हैं।',
        closing: 'जब अच्छी तरह से प्रबंधित किया जाता है, तो प्राप्य खाते कार्यशील पूंजी को मजबूत करते हैं, राजस्व की रक्षा करते हैं और समग्र व्यावसायिक स्थिरता का समर्थन करते हैं।',
      },
      faq: {
        heading: 'अक्सर पूछे जाने वाले प्रश्न',
        subtitle: 'हमारे संग्रह, सलाहकारी, और सगाई मॉडल के बारे में त्वरित उत्तर।',
        q1: 'क्या आपकी वसूली प्रक्रिया DISCOM या PSU के साथ हमारे दीर्घकालिक संबंध को नुकसान पहुंचाएगी?',
        a1: 'नहीं। हम "डिप्लोमैटिक कॉशन" रणनीति अपनाते हैं। हम मानते हैं कि ये एजेंसियां आपके भविष्य के ग्राहक हैं। हमारा दृष्टिकोण पेशेवर वार्ता के माध्यम से दस्तावेज़ीकरण अड़चनों और प्रक्रियात्मक बाधाओं को हल करने पर केंद्रित है, ताकि भविष्य के टेंडर के लिए आपकी प्रतिष्ठा बनी रहे।',
        q2: '"कोई संग्रह नहीं, कोई शुल्क नहीं" मॉडल कैसे काम करता है?',
        a2: 'यह अतिदेय वसूली के लिए 95% जोखिम-मुक्त मॉडल है। आप कोई अग्रिम सेवा शुल्क नहीं देते; हमारा सफलता शुल्क आपके बैंक खाते में वास्तव में प्राप्त राशि का पूर्व-सहमत प्रतिशत है। यदि हम वसूली नहीं करते, तो आप भुगतान नहीं करते। (नोट: निश्चित शुल्क संरचना केवल चल रहे तकनीकी संपर्क या टेंडर प्रबंधन सेवाओं पर लागू)।',
        q3: 'यदि हमारे पास पहले से आंतरिक लेखा विभाग है तो आउटसोर्स क्यों करें?',
        a3: 'आंतरिक टीमें अक्सर डेस्क पर बंधी रहती हैं। हम PSU नौकरशाही के माध्यम से फाइलें आगे बढ़ाने के लिए आवश्यक "ऑन-ग्राउंड" उपस्थिति प्रदान करते हैं। आउटसोर्सिंग आपकी निश्चित ओवरहेड लागत को परिवर्तनीय, प्रदर्शन-आधारित खर्च में बदल देती है, आपकी टीम को मुख्य वित्तीय योजना और निष्पादन के लिए मुक्त करती है।',
        q4: 'पावर और सोलर सेक्टर में आप DSO और कैश फ्लो को विशेष रूप से कैसे सुधारते हैं?',
        a4: 'हम प्रगतिशील भुगतान, अंतिम बिल और रिटेंशन/PBG की रिहाई का आक्रामक लेकिन अनुपालनपूर्ण पीछा करते हैं। उपयोगिताओं और DISCOM से होने वाली देरी को कम करके, हम आपके डेज़ सेल्स आउटस्टैंडिंग (DSO) को कम करते हैं और बैड डेब्ट काटते हैं, नई परियोजनाओं में पुनर्निवेश के लिए आवश्यक तरलता बढ़ाते हैं।',
        q5: 'विवादित भुगतान या L.D. (लेट डिलीवरी) जुर्माना आप कैसे संभालते हैं?',
        a5: 'हम अनुबंध और भुगतानकर्ता इतिहास में गहराई से जाते हैं। यह पहचानकर कि देरी नौकरशाही बाधाओं के कारण थी न कि विक्रेता दोष के कारण, हम जुर्माना कम करने और महंगे कानूनी मध्यस्थता तक पहुंचे बिना विवादों को हल करने के लिए आवश्यक दस्तावेज़ीकरण प्रदान करते हैं।',
        q6: 'क्या आप पुरानी रिटेंशन मनी और PBG की रिहाई में मदद कर सकते हैं?',
        a6: 'हां। यह हमारी मुख्य ताकतों में से एक है। हम लंबे समय से लंबित रिटेंशन फंड और परफॉर्मेंस बैंक गारंटी (PBG) का पता लगाने में विशेषज्ञ हैं जो परियोजना पूर्ण होने के वर्षों बाद भी सिस्टम में "अटके" रह जाते हैं।',
        q7: 'हम अपने मामलों की स्थिति पर कैसे अपडेट रहें?',
        a7: 'पारदर्शिता हमारी सेवा का एक स्तंभ है। आपको नियमित MIS (मैनेजमेंट इन्फॉर्मेशन सिस्टम) रिपोर्ट मिलेंगी, जिसमें हर इनवॉइस के लिए एजिंग विश्लेषण और विस्तृत स्थिति नोट शामिल होंगे, जिससे आपको अपने प्राप्य का स्पष्ट, डेटा-संचालित दृश्य मिलेगा।',
        q8: 'आपका "पोल-टू-पोल" सेवा मॉडल क्या है?',
        a8: 'यह हमारी अंत-से-अंत भागीदारी को संदर्भित करता है—"पहले पोल" (टेंडर और तकनीकी दस्तावेज़ीकरण) से "अंतिम पोल" (अंतिम भुगतान वसूली और अनुबंध समापन) तक। हम पूरे जीवनचक्र का प्रबंधन करते हैं ताकि किसी भी चरण में कोई वित्तीय रिसाव न हो।',
        q9: 'आप "जानबूझकर" बनाम "वास्तविक" भुगतान देरी को कैसे वर्गीकृत करते हैं?',
        a9: 'हम देरी को वर्गीकृत करने के लिए 20+ वर्षों के भुगतानकर्ता इतिहास और स्थानीय खुफिया जानकारी का उपयोग करते हैं। यदि देरी वास्तविक है (बजट मुद्दे), हम यथार्थवादी भुगतान समयरेखा पर बातचीत करते हैं। यदि यह जानबूझकर है (प्रशासनिक रुकावट), हम मामले को उचित कूटनीतिक और आधिकारिक चैनलों के माध्यम से बढ़ाते हैं।',
        q10: 'क्या आपकी सेवा किसी राज्य तक सीमित है या पैन-इंडिया है?',
        a10: 'जबकि हम गर्व से जयपुर में स्थित हैं, हमारा नेटवर्क और परिचालन क्षमता पैन-इंडिया है। हमारे पास देश भर में किसी भी राज्य में उपयोगिताओं और सरकारी विभागों का फॉलो-अप करने की विशेषज्ञता और स्थानीय पहुंच है।',
        q11: 'जब सरकारी विभाग "बजट की कमी" या "केंद्र से धन प्राप्त नहीं हुआ" का दावा करता है तो आप ऐसे मामलों को कैसे संभालते हैं?',
        a11: 'यहीं हमारी विशिष्ट खुफिया जानकारी काम आती है। हम केवल "नहीं" को जवाब के रूप में स्वीकार नहीं करते। हम राज्य और केंद्रीय आवंटन के माध्यम से धन के प्रवाह को ट्रैक करते हैं। अक्सर, हम सभी अनुपालन दस्तावेजों को "भुगतान-तैयार" सुनिश्चित करके विभाग को आपकी फाइल को प्राथमिकता देने में मदद करते हैं, ताकि उनके लिए अधूरी दूसरी फाइलों पर आपके इनवॉइस के लिए उपलब्ध धन का उपयोग करना आसान हो जाए।',
        q12: 'क्या आपका दृष्टिकोण पूरी तरह से मैनुअल है, या ट्रैकिंग के लिए प्रौद्योगिकी का उपयोग करते हैं?',
        a12: 'हम हाइब्रिड दृष्टिकोण का उपयोग करते हैं। जबकि अंतिम "पुश" हमेशा व्यक्तिगत और कूटनीतिक होता है, हम एजिंग चक्र और भुगतान माइलस्टोन की निगरानी के लिए आंतरिक ट्रैकिंग टूल का उपयोग करते हैं। यह हमें आपको डेटा-संचालित MIS रिपोर्ट प्रदान करने में सक्षम बनाता है जो आपके CFO को बहुत अधिक सटीकता के साथ कैश फ्लो का पूर्वानुमान लगाने में मदद करती हैं।',
        q13: 'अनुबंध के "क्लोजर" चरण में आप कैसे सहायता करते हैं?',
        a13: 'अधिकांश एजेंसियां इनवॉइस संग्रह पर रुक जाती हैं। हम "लास्ट माइल" क्लोजर संभालते हैं, जिसमें खातों का समाधान, "नो ड्यूज सर्टिफिकेट" प्राप्त करना और लंबे समय से अटके परफॉर्मेंस बैंक गारंटी (PBG) को रिलीज़ करने का महत्वपूर्ण कार्य शामिल है। हम सुनिश्चित करते हैं कि अनुबंध विभाग के रिकॉर्ड में कानूनी और वित्तीय रूप से बंद हो।',
        q14: 'क्या आप GST और कर-संबंधित भुगतान समाधान में हमारी मदद कर सकते हैं?',
        a14: 'हां। चूंकि हम हर भुगतान के लिए "परफेक्ट डॉक्यूमेंटेशन" सुनिश्चित करते हैं, हम आपकी रियलाइजेशन को GST फाइलिंग के साथ संरेखित करने में मदद करते हैं। हम सुनिश्चित करते हैं कि विभाग आवश्यक प्रमाणपत्र (जैसे TDS या GST TDS प्रमाणपत्र) प्रदान करे ताकि आपके कर ऑडिट साफ रहें और आपके इनपुट टैक्स क्रेडिट सुरक्षित रहें।',
        q15: 'NB Aurum Solutions को आउटसोर्स करने के मुख्य लाभ क्या हैं?',
        a15: '• अतिदेय भुगतान और बैड डेब्ट में कमी/समाप्ति\n• कूटनीतिक लेकिन दृढ़ दृष्टिकोण के माध्यम से तेज़ संग्रह, बेहतर हितधारक संबंध\n• व्यवस्थित ट्रैकिंग: इनवॉइस/एजिंग/एस्केलेशन/कटौती ट्रैकर, समाधान\n• त्वरित क्वेरी समाधान और टेम्पलेटेड रिमाइंडर\n• प्रक्रिया स्वचालन, लगातार विश्लेषण और देरी के कारणों की पहचान\n• पूर्ण अनुपालन/पारदर्शिता/दस्तावेज़ीकरण\n• भविष्य के व्यावसायिक अवसरों को संरक्षित करते हुए नैतिक वसूली',
        q16: 'क्या मैं NB Aurum Solutions को भुगतान संग्रह आउटसोर्स करने पर नियंत्रण खो दूंगा?',
        a16: 'नहीं—साझेदारी आपकी निगरानी बनाए रखती है। हम आपके अनुबंध दिशानिर्देशों के अनुसार काम करते हैं, नियमित MIS (इनवॉइस ट्रैकर, एजिंग विश्लेषण, स्टेटमेंट) प्रदान करते हैं। आप स्कोप तय करते हैं: पूर्ण अंत-से-अंत या विशिष्ट गतिविधियां। पारदर्शिता पूर्ण दृश्यता और नियंत्रण सुनिश्चित करती है।',
        viewMore: 'अधिक देखें',
        viewMoreHint: 'एक और सवाल है? संपर्क पृष्ठ पर हमसे पूछें।',
      },
      onboarding: {
        heading: 'हमारी निर्बाध ऑनबोर्डिंग प्रक्रिया',
        getStarted: 'शुरू करें',
        talkToUs: 'हमसे बात करें',
      },
    },
    about: {
      heading: 'NB Aurum Solutions के बारे में',
      lead: 'भुगतान संग्रह और सलाहकारी में आपका विश्वसनीय साथी—पूरे भारत में पावर, सोलर, टेलीकॉम, रेलवे, PSU और सरकारी परियोजनाओं में विशेषज्ञता।',
      mission: {
        title: 'हमारा मिशन',
        text: 'हम भुगतान वसूली और संग्रह में अनुशासन, पारदर्शिता और परिणाम लाते हैं। हम पहली बार प्रक्रियाओं को सही सेट करने, मजबूत ग्राहक संबंधों, पूर्ण नीति और दस्तावेज़ अनुपालन, और "कभी न कहें" रवैये में विश्वास करते हैं—ताकि आपका नकदी प्रवाह सुरक्षित हो और आपके अनुबंध साफ-सुथरे तरीके से बंद हों।',
        standFor: 'हम किसके लिए खड़े हैं',
        standForText: 'NB Aurum Solutions 20+ वर्षों के अनुभव पर बनाया गया है। हम रणनीतिक संपर्क, आक्रामक भुगतान वसूली, विवाद प्रबंधन, और MIS-नेतृत्व वाले अनुपालन पर ध्यान केंद्रित करते हैं—ताकि आपको एकल संपर्क बिंदु से अंत-से-अंत सेवा मिले जबकि आपकी टीम विकास पर ध्यान केंद्रित करती है।',
        whoWeAre: 'हम कौन हैं',
      },
      compliance: {
        heading: 'अनुपालन, सुरक्षा और पारदर्शिता',
        lead: 'पूर्ण नीति और दस्तावेज़ अनुपालन, नैतिक वसूली प्रथाएं, और डेटा पारदर्शिता—ताकि आप हर कदम पर भरोसा कर सकें।',
        complianceControls: {
          title: 'अनुपालन और नियंत्रण',
          text: 'गतिविधियां नीति, दस्तावेज़ीकरण मानकों, और नैतिक वसूली प्रथाओं का सख्ती से पालन करती हैं। नियमित MIS रिपोर्ट, इनवॉइस ट्रैकर, एजिंग विश्लेषण, और समाधान विवरण सब कुछ लेखापरीक्षा-तैयार रखते हैं।',
        },
        dataConfidentiality: {
          title: 'डेटा और गोपनीयता',
          text: 'आपका व्यावसायिक डेटा गोपनीय रहता है। हम कठोर प्रक्रियाओं, स्पष्ट अधिकार, और एकल संपर्क बिंदु का उपयोग करते हैं ताकि आंतरिक संसाधन विकास पर ध्यान केंद्रित कर सकें जबकि हम संपर्क और वसूली का प्रबंधन करते हैं।',
        },
        scalability: {
          title: 'मापनीयता',
          text: 'पेशेवरों के देशव्यापी नेटवर्क के साथ पूरे भारत में क्षमता। हम आपके परियोजना फुटप्रिंट के साथ स्केल करते हैं—पावर, सोलर, टेलीकॉम, रेलवे, PSU और सरकार—संबंध प्रबंधन या अनुपालन से समझौता किए बिना।',
        },
      },
      values: {
        heading: 'हमारी यात्रा और मूल्य',
        lead: 'नींव से आज तक—हम कैसे काम करते हैं और हम किसके लिए खड़े हैं।',
        howWeDeliver: {
          title: 'हम कैसे वितरित करते हैं',
          strategicLiaison: {
            title: 'रणनीतिक संपर्क',
            text: 'उपयोगिता और प्राधिकरण समन्वय, तकनीकी प्रस्तुति, और परिचालन सुव्यवस्थितीकरण ताकि परियोजनाएं देरी न करें।',
          },
          paymentRealization: {
            title: 'भुगतान वसूली',
            text: 'जीवनचक्र बिलिंग, संपत्ति वसूली (रिटेंशन, EMD, BGs), और कोई संग्रह नहीं, कोई शुल्क नहीं आधार पर जोखिम-मुक्त संग्रह।',
          },
          disputeClosure: {
            title: 'विवाद और समापन',
            text: 'विवाद समाधान, कूटनीतिक वार्ता, और समाधान और प्रमाणन के साथ पूर्ण अनुबंध समापन तक सहायता।',
          },
        },
        coreValues: {
          title: 'मुख्य मूल्य',
          value1: 'ईमानदारी पहले—प्रक्रिया-संचालित अनुपालन और नैतिक वसूली।',
          value2: 'पहली बार प्रक्रियाओं को सही सेट करें; कोई शॉर्टकट नहीं।',
          value3: 'दीर्घकालिक संबंधों को संरक्षित करने के लिए कूटनीतिक लेकिन दृढ़ वार्ता।',
          value4: 'MIS और नियमित रिपोर्टिंग के माध्यम से पूर्ण पारदर्शिता।',
        },
      },
      differentiates: {
        heading: 'जो NB Aurum Solutions को अलग बनाता है',
        lead: 'अतुल्य डोमेन विशेषज्ञता, देशव्यापी क्षमता, और प्रतिष्ठा-संरक्षण दृष्टिकोण।',
        domainExpertise: {
          title: 'डोमेन विशेषज्ञता',
          text: 'सरकारी कंपनियों, रेलवे और PSU में लक्षित सेक्टर अनुभव। गहरी प्रक्रिया ज्ञान जो आंतरिक रिपोर्टिंग और MIS सटीकता में सुधार करता है।',
        },
        panIndia: {
          title: 'पूरे भारत में क्षमता',
          text: 'पेशेवरों का देशव्यापी नेटवर्क और मजबूत संबंध प्रबंधन जटिल भुगतान अड़चनों को हल करने के लिए—जहां भी आपकी परियोजनाएं हों।',
        },
        riskFree: {
          title: 'जोखिम-मुक्त मॉडल',
          text: 'परिणाम-आधारित मूल्य निर्धारण, शून्य अग्रिम लागत, और प्रदर्शन-संचालित वसूली। आप तब भुगतान करते हैं जब हम वितरित करते हैं—ताकि अपनाना निर्बाध और कम जोखिम हो।',
        },
      },
      getStarted: {
        heading: 'शुरू करने के लिए तैयार हैं?',
        lead: 'अनुशासित भुगतान संग्रह और सलाहकारी के लिए NB Aurum Solutions के साथ साझेदारी करें। शून्य अग्रिम लागत, प्रदर्शन-आधारित वसूली।',
        getStarted: 'शुरू करें',
        getInTouch: 'संपर्क करें',
      },
    },
    whoWeAre: {
      eyebrow: 'हमारी कहानी',
      heading: 'हम कौन हैं',
      lead: 'हम भुगतान संग्रह और सलाहकारी में आपके विश्वसनीय साथी हैं—पूरे भारत में पावर, सोलर, टेलीकॉम, रेलवे, PSU और सरकारी परियोजनाओं में 20+ वर्षों का अनुभव।',
      pillars: {
        heading: 'जो हमें चलाता है',
        why: {
          title: 'हम यह क्यों करते हैं',
          text: 'हमने टीमों को देरी से भुगतान, फंसी हुई रिटेंशन मनी, और उपयोगिताओं और प्राधिकरणों के साथ जटिल संपर्क से संघर्ष करते देखा। NB Aurum Solutions प्रक्रियाओं को सही सेट करने, देय राशि को वसूल करने, और पूर्ण अनुपालन के साथ अनुबंध बंद करने के लिए मौजूद है—ताकि आप विकास पर ध्यान केंद्रित कर सकें।',
        },
        who: {
          title: 'हम किसकी सेवा करते हैं',
          text: 'पावर, सोलर, टेलीकॉम, रेलवे, PSU और सरकारी परियोजनाओं में कंपनियां—पूरे भारत में। हम वित्त नेताओं, परियोजना टीमों, और संचालन की सेवा करते हैं जिन्हें आक्रामक भुगतान वसूली, विवाद समाधान, और अंत-से-अंत संग्रह सहायता की आवश्यकता है।',
        },
        how: {
          title: 'हम कैसे काम करते हैं',
          text: 'समर्पित संपर्क, नियमित MIS, कूटनीतिक वार्ता, और "कभी न कहें" रवैया। हम जमीनी विशेषज्ञता को प्रक्रिया-संचालित अनुपालन के साथ जोड़ते हैं ताकि आपको तेजी से संग्रह और संरक्षित संबंध मिलें।',
        },
      },
      philosophy: {
        heading: 'हमारा दर्शन और प्रतिबद्धता',
        lead: 'ईमानदारी पहले, पूर्ण अनुपालन, और प्रतिष्ठा-संरक्षण वसूली।',
        philosophyTitle: 'हमारा दर्शन',
        philosophyText: 'पहली बार प्रक्रियाओं को सही सेट करें। मजबूत ग्राहक संबंध बनाएं। पूर्ण नीति और दस्तावेज़ अनुपालन सुनिश्चित करें। अंत-से-अंत सेवा वितरित करें। हम "कभी न कहें" रवैये के साथ काम करते हैं—ताकि आपका नकदी प्रवाह सुरक्षित हो और आपके अनुबंध बिना घर्षण के बंद हों।',
        commitmentTitle: 'जिसके लिए हम प्रतिबद्ध हैं',
        diplomaticApproach: 'कूटनीतिक दृष्टिकोण: दीर्घकालिक व्यावसायिक संबंधों को संरक्षित करने के लिए दृढ़ लेकिन विनम्र वार्ता।',
        ethicalRecovery: 'नैतिक वसूली: पूर्ण पारदर्शिता, MIS रिपोर्टिंग, और नीति और दस्तावेज़ीकरण मानकों के साथ अनुपालन।',
        riskFreeModel: 'जोखिम-मुक्त मॉडल: कोई संग्रह नहीं, कोई शुल्क नहीं—ताकि आप तभी भुगतान करें जब हम वितरित करें।',
        singlePoint: 'एकल संपर्क बिंदु: समर्पित टीम ताकि आपके आंतरिक संसाधन विकास पर ध्यान केंद्रित करें।',
      },
      values: {
        integrityFirst: 'ईमानदारी पहले',
        fullCompliance: 'पूर्ण अनुपालन',
        reputationPreserving: 'प्रतिष्ठा-संरक्षण',
        neverSayNo: 'कभी न कहें',
        panIndia: 'पूरे भारत में',
      },
      cta: {
        heading: 'अपने नकदी प्रवाह को सुरक्षित करने के लिए तैयार हैं?',
        lead: 'शून्य जोखिम प्रदर्शन मॉडल, सेक्टर विशेषज्ञता, और अंत-से-अंत जीवनचक्र कवरेज। आपके बकाया। हमारा कर्तव्य।',
        getInTouch: 'संपर्क करें',
        viewEngagement: 'सगाई विकल्प देखें',
      },
    },
  },
}

const MarketingLanguageContext = createContext(null)

export function MarketingLanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY)
      if (stored === 'hi' || stored === 'en') return stored
    } catch {}
    return 'en'
  })

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language)
    } catch {}
  }, [language])

  const setLanguage = useCallback((lang) => {
    if (lang === 'en' || lang === 'hi') setLanguageState(lang)
  }, [])

  const t = useCallback(
    (key) => {
      const keys = key.split('.')
      let obj = translations[language]
      for (const k of keys) {
        obj = obj?.[k]
      }
      return obj ?? key
    },
    [language]
  )

  const value = {
    language,
    setLanguage,
    t,
    isHindi: language === 'hi',
  }

  return (
    <MarketingLanguageContext.Provider value={value}>
      {children}
    </MarketingLanguageContext.Provider>
  )
}

export function useMarketingLanguage() {
  const ctx = useContext(MarketingLanguageContext)
  if (!ctx) {
    throw new Error('useMarketingLanguage must be used within MarketingLanguageProvider')
  }
  return ctx
}
